/* Auto-generated by genmsg_cpp for file /home/adam/ros_workspace/ros_kf_stack/kf_yaw_kf/msg/Compass.msg */
#ifndef KF_YAW_KF_MESSAGE_COMPASS_H
#define KF_YAW_KF_MESSAGE_COMPASS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kf_yaw_kf
{
template <class ContainerAllocator>
struct Compass_ {
  typedef Compass_<ContainerAllocator> Type;

  Compass_()
  : header()
  , compass(0.0)
  , heading(0.0)
  , stddev(0.0)
  {
  }

  Compass_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , compass(0.0)
  , heading(0.0)
  , stddev(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _compass_type;
  float compass;

  typedef float _heading_type;
  float heading;

  typedef float _stddev_type;
  float stddev;


  typedef boost::shared_ptr< ::kf_yaw_kf::Compass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kf_yaw_kf::Compass_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Compass
typedef  ::kf_yaw_kf::Compass_<std::allocator<void> > Compass;

typedef boost::shared_ptr< ::kf_yaw_kf::Compass> CompassPtr;
typedef boost::shared_ptr< ::kf_yaw_kf::Compass const> CompassConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kf_yaw_kf::Compass_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kf_yaw_kf::Compass_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kf_yaw_kf

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kf_yaw_kf::Compass_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kf_yaw_kf::Compass_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kf_yaw_kf::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6128f9329b98d64881b65764b2d6fdbe";
  }

  static const char* value(const  ::kf_yaw_kf::Compass_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6128f9329b98d648ULL;
  static const uint64_t static_value2 = 0x81b65764b2d6fdbeULL;
};

template<class ContainerAllocator>
struct DataType< ::kf_yaw_kf::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kf_yaw_kf/Compass";
  }

  static const char* value(const  ::kf_yaw_kf::Compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kf_yaw_kf::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 compass\n\
float32 heading\n\
float32 stddev\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kf_yaw_kf::Compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kf_yaw_kf::Compass_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kf_yaw_kf::Compass_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kf_yaw_kf::Compass_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.compass);
    stream.next(m.heading);
    stream.next(m.stddev);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Compass_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kf_yaw_kf::Compass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kf_yaw_kf::Compass_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "compass: ";
    Printer<float>::stream(s, indent + "  ", v.compass);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "stddev: ";
    Printer<float>::stream(s, indent + "  ", v.stddev);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KF_YAW_KF_MESSAGE_COMPASS_H

